BEGIN;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM pg_type t
        JOIN pg_enum e ON e.enumtypid = t.oid
        WHERE t.typname = 'listing_type'
          AND e.enumlabel = 'DONATION'
    ) AND NOT EXISTS (
        SELECT 1
        FROM pg_type t
        JOIN pg_enum e ON e.enumtypid = t.oid
        WHERE t.typname = 'listing_type'
          AND e.enumlabel = 'GIFT'
    ) THEN
        ALTER TYPE listing_type RENAME VALUE 'DONATION' TO 'GIFT';
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'handoff_status') THEN
        CREATE TYPE handoff_status AS ENUM ('PENDING', 'OWNER_CONFIRMED', 'RECIPIENT_CONFIRMED', 'COMPLETED', 'CANCELLED');
    END IF;
END$$;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'plant_listings'
          AND column_name = 'donation_notes'
    ) AND NOT EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'plant_listings'
          AND column_name = 'gift_notes'
    ) THEN
        ALTER TABLE public.plant_listings RENAME COLUMN donation_notes TO gift_notes;
    END IF;
END$$;

ALTER TABLE public.plant_listings DROP CONSTRAINT IF EXISTS plant_listings_sale_requires_store_chk;
ALTER TABLE public.plant_listings DROP CONSTRAINT IF EXISTS plant_listings_non_sale_requires_owner_chk;
ALTER TABLE public.plant_listings DROP CONSTRAINT IF EXISTS plant_listings_sale_requires_price_chk;
ALTER TABLE public.plant_listings DROP CONSTRAINT IF EXISTS plant_listings_non_sale_clears_price_chk;
ALTER TABLE public.plant_listings DROP CONSTRAINT IF EXISTS plant_listings_sitting_requires_dates_chk;
ALTER TABLE public.plant_listings DROP CONSTRAINT IF EXISTS plant_listings_non_sitting_clears_dates_chk;

ALTER TABLE public.plant_listings
    ADD CONSTRAINT plant_listings_sale_requires_price_chk
        CHECK (
            (listing_type <> 'SALE')
            OR
            (sale_price IS NOT NULL AND currency_code IS NOT NULL)
        ),
    ADD CONSTRAINT plant_listings_non_sale_clears_price_chk
        CHECK (
            (listing_type = 'SALE')
            OR
            (sale_price IS NULL AND currency_code IS NULL)
        ),
    ADD CONSTRAINT plant_listings_sitting_requires_dates_chk
        CHECK (
            (listing_type <> 'SITTING_REQUEST')
            OR
            (sitting_start_date IS NOT NULL AND sitting_end_date IS NOT NULL)
        ),
    ADD CONSTRAINT plant_listings_non_sitting_clears_dates_chk
        CHECK (
            (listing_type = 'SITTING_REQUEST')
            OR
            (sitting_start_date IS NULL AND sitting_end_date IS NULL)
        );

CREATE TABLE IF NOT EXISTS public.listing_handoffs (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    listing_id                  BIGINT NOT NULL UNIQUE REFERENCES public.plant_listings(id) ON DELETE CASCADE,
    owner_user_id               UUID NOT NULL REFERENCES public.owner_profiles(user_id) ON DELETE RESTRICT,
    recipient_user_id           UUID NOT NULL REFERENCES public.users(id) ON DELETE RESTRICT,
    swap_proposal_id            BIGINT UNIQUE REFERENCES public.swap_proposals(id) ON DELETE SET NULL,
    amount                      NUMERIC(10,2),
    currency_code               CHAR(3),
    status                      handoff_status NOT NULL DEFAULT 'PENDING',
    notes                       TEXT,
    owner_confirmed_at          TIMESTAMPTZ,
    recipient_confirmed_at      TIMESTAMPTZ,
    completed_at                TIMESTAMPTZ,
    cancelled_at                TIMESTAMPTZ,
    created_by_user_id          UUID NOT NULL REFERENCES public.users(id) ON DELETE RESTRICT,
    created_at                  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at                  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT listing_handoffs_amount_chk CHECK (amount IS NULL OR amount >= 0),
    CONSTRAINT listing_handoffs_distinct_parties_chk CHECK (owner_user_id <> recipient_user_id)
);

CREATE TABLE IF NOT EXISTS public.listing_handoff_reviews (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    handoff_id                  BIGINT NOT NULL REFERENCES public.listing_handoffs(id) ON DELETE CASCADE,
    reviewer_user_id            UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    reviewee_user_id            UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    rating                      INTEGER NOT NULL CHECK (rating BETWEEN 1 AND 5),
    review_text                 TEXT,
    created_at                  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at                  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT listing_handoff_reviews_distinct_users_chk CHECK (reviewer_user_id <> reviewee_user_id),
    CONSTRAINT listing_handoff_reviews_unique UNIQUE (handoff_id, reviewer_user_id)
);

CREATE OR REPLACE FUNCTION public.validate_plant_listing()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
DECLARE
    v_current_owner UUID;
BEGIN
    IF NEW.owner_user_id IS NOT NULL THEN
        SELECT current_owner_user_id
        INTO v_current_owner
        FROM public.plants
        WHERE id = NEW.plant_id;

        IF v_current_owner IS NULL THEN
            RAISE EXCEPTION 'Plant % does not exist', NEW.plant_id;
        END IF;

        IF v_current_owner <> NEW.owner_user_id THEN
            RAISE EXCEPTION 'Owner listing must reference a plant currently owned by that owner';
        END IF;
    END IF;

    IF NEW.listing_type = 'SWAP' AND NEW.owner_user_id IS NULL THEN
        RAISE EXCEPTION 'Swap listings must belong to a normal owner';
    END IF;

    IF NEW.listing_type = 'GIFT' AND NEW.owner_user_id IS NULL THEN
        RAISE EXCEPTION 'Gift listings must belong to a normal owner';
    END IF;

    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_validate_plant_listing ON public.plant_listings;
CREATE TRIGGER trg_validate_plant_listing
    BEFORE INSERT OR UPDATE ON public.plant_listings
    FOR EACH ROW EXECUTE FUNCTION public.validate_plant_listing();

CREATE OR REPLACE FUNCTION public.validate_listing_application()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
DECLARE
    v_listing_type listing_type;
BEGIN
    SELECT listing_type
    INTO v_listing_type
    FROM public.plant_listings
    WHERE id = NEW.listing_id;

    IF v_listing_type IS NULL THEN
        RAISE EXCEPTION 'Listing % does not exist', NEW.listing_id;
    END IF;

    IF v_listing_type <> 'SITTING_REQUEST' THEN
        RAISE EXCEPTION 'Applications are only valid for sitting request listings';
    END IF;

    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_validate_listing_application ON public.listing_applications;
CREATE TRIGGER trg_validate_listing_application
    BEFORE INSERT OR UPDATE ON public.listing_applications
    FOR EACH ROW EXECUTE FUNCTION public.validate_listing_application();

CREATE OR REPLACE FUNCTION public.validate_swap_proposal()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
DECLARE
    v_listing_type listing_type;
    v_listing_plant_id BIGINT;
BEGIN
    SELECT listing_type, plant_id
    INTO v_listing_type, v_listing_plant_id
    FROM public.plant_listings
    WHERE id = NEW.listing_id;

    IF v_listing_type IS NULL THEN
        RAISE EXCEPTION 'Listing % does not exist', NEW.listing_id;
    END IF;

    IF v_listing_type <> 'SWAP' THEN
        RAISE EXCEPTION 'Swap proposals are only valid for swap listings';
    END IF;

    IF v_listing_plant_id = NEW.offered_plant_id THEN
        RAISE EXCEPTION 'Cannot offer the same plant that is already listed';
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM public.plants p
        WHERE p.id = NEW.offered_plant_id
          AND p.current_owner_user_id = NEW.proposer_owner_user_id
          AND p.is_active = TRUE
          AND p.archived_at IS NULL
    ) THEN
        RAISE EXCEPTION 'Swap proposals must use an active plant owned by the proposer';
    END IF;

    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_validate_swap_proposal ON public.swap_proposals;
CREATE TRIGGER trg_validate_swap_proposal
    BEFORE INSERT OR UPDATE ON public.swap_proposals
    FOR EACH ROW EXECUTE FUNCTION public.validate_swap_proposal();

CREATE OR REPLACE FUNCTION public.validate_contract()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
DECLARE
    v_listing_type listing_type;
    v_listing_owner UUID;
    v_application_listing_id BIGINT;
    v_application_user UUID;
    v_application_status application_status;
BEGIN
    IF NEW.listing_id IS NULL AND NEW.application_id IS NULL THEN
        RAISE EXCEPTION 'Contracts must reference a sitting listing or accepted application';
    END IF;

    IF NEW.listing_id IS NOT NULL THEN
        SELECT listing_type, owner_user_id
        INTO v_listing_type, v_listing_owner
        FROM public.plant_listings
        WHERE id = NEW.listing_id;

        IF v_listing_type IS NULL THEN
            RAISE EXCEPTION 'Listing % does not exist', NEW.listing_id;
        END IF;

        IF v_listing_type <> 'SITTING_REQUEST' THEN
            RAISE EXCEPTION 'Contracts can only be created for sitting request listings';
        END IF;

        IF v_listing_owner <> NEW.owner_user_id THEN
            RAISE EXCEPTION 'Contract owner must match listing owner';
        END IF;
    END IF;

    IF NEW.application_id IS NOT NULL THEN
        SELECT la.listing_id, la.applicant_user_id, la.status
        INTO v_application_listing_id, v_application_user, v_application_status
        FROM public.listing_applications la
        WHERE la.id = NEW.application_id;

        IF v_application_listing_id IS NULL THEN
            RAISE EXCEPTION 'Application % does not exist', NEW.application_id;
        END IF;

        IF v_application_status <> 'ACCEPTED' THEN
            RAISE EXCEPTION 'Contracts can only be created from accepted applications';
        END IF;

        IF NEW.listing_id IS NOT NULL AND v_application_listing_id <> NEW.listing_id THEN
            RAISE EXCEPTION 'Contract listing and application listing must match';
        END IF;

        IF NEW.sitter_user_id <> v_application_user THEN
            RAISE EXCEPTION 'Contract sitter must match the accepted applicant';
        END IF;
    END IF;

    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_validate_contract ON public.contracts;
CREATE TRIGGER trg_validate_contract
    BEFORE INSERT OR UPDATE ON public.contracts
    FOR EACH ROW EXECUTE FUNCTION public.validate_contract();

CREATE OR REPLACE FUNCTION public.validate_listing_handoff()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
DECLARE
    v_listing_type listing_type;
    v_listing_owner UUID;
    v_proposer UUID;
    v_swap_status swap_status;
BEGIN
    SELECT listing_type, owner_user_id
    INTO v_listing_type, v_listing_owner
    FROM public.plant_listings
    WHERE id = NEW.listing_id;

    IF v_listing_type IS NULL THEN
        RAISE EXCEPTION 'Listing % does not exist', NEW.listing_id;
    END IF;

    IF v_listing_type NOT IN ('SALE', 'GIFT', 'SWAP') THEN
        RAISE EXCEPTION 'Handoffs are only valid for sale, gift, and swap listings';
    END IF;

    IF v_listing_owner IS NULL THEN
        RAISE EXCEPTION 'Only owner-backed listings can create peer handoffs';
    END IF;

    IF NEW.owner_user_id <> v_listing_owner THEN
        RAISE EXCEPTION 'Handoff owner must match listing owner';
    END IF;

    IF v_listing_type = 'SALE' THEN
        IF NEW.amount IS NULL OR NEW.currency_code IS NULL THEN
            RAISE EXCEPTION 'Sale handoffs require an amount and currency';
        END IF;
        IF NEW.swap_proposal_id IS NOT NULL THEN
            RAISE EXCEPTION 'Sale handoffs cannot reference swap proposals';
        END IF;
    ELSIF v_listing_type = 'GIFT' THEN
        IF NEW.amount IS NOT NULL OR NEW.currency_code IS NOT NULL THEN
            RAISE EXCEPTION 'Gift handoffs cannot record a sale amount';
        END IF;
        IF NEW.swap_proposal_id IS NOT NULL THEN
            RAISE EXCEPTION 'Gift handoffs cannot reference swap proposals';
        END IF;
    ELSE
        IF NEW.swap_proposal_id IS NULL THEN
            RAISE EXCEPTION 'Swap handoffs require an accepted swap proposal';
        END IF;
        IF NEW.amount IS NOT NULL OR NEW.currency_code IS NOT NULL THEN
            RAISE EXCEPTION 'Swap handoffs do not support cash amounts';
        END IF;

        SELECT proposer_owner_user_id, status
        INTO v_proposer, v_swap_status
        FROM public.swap_proposals
        WHERE id = NEW.swap_proposal_id
          AND listing_id = NEW.listing_id;

        IF v_proposer IS NULL THEN
            RAISE EXCEPTION 'Swap handoff must reference a swap proposal for the same listing';
        END IF;

        IF v_swap_status <> 'ACCEPTED' THEN
            RAISE EXCEPTION 'Swap handoff requires an accepted swap proposal';
        END IF;

        IF NEW.recipient_user_id <> v_proposer THEN
            RAISE EXCEPTION 'Swap handoff recipient must match the accepted proposer';
        END IF;
    END IF;

    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_validate_listing_handoff ON public.listing_handoffs;
CREATE TRIGGER trg_validate_listing_handoff
    BEFORE INSERT OR UPDATE ON public.listing_handoffs
    FOR EACH ROW EXECUTE FUNCTION public.validate_listing_handoff();

CREATE OR REPLACE FUNCTION public.confirm_listing_handoff(p_handoff_id BIGINT)
RETURNS public.listing_handoffs
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_actor UUID := auth.uid();
    v_now TIMESTAMPTZ := NOW();
    v_handoff public.listing_handoffs%ROWTYPE;
    v_listing public.plant_listings%ROWTYPE;
    v_swap_offered_plant_id BIGINT;
BEGIN
    IF v_actor IS NULL THEN
        RAISE EXCEPTION 'Authentication required';
    END IF;

    SELECT *
    INTO v_handoff
    FROM public.listing_handoffs
    WHERE id = p_handoff_id
    FOR UPDATE;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Handoff % does not exist', p_handoff_id;
    END IF;

    IF v_actor <> v_handoff.owner_user_id AND v_actor <> v_handoff.recipient_user_id THEN
        RAISE EXCEPTION 'Only handoff participants can confirm completion';
    END IF;

    IF v_handoff.status = 'CANCELLED' THEN
        RAISE EXCEPTION 'Cancelled handoffs cannot be confirmed';
    END IF;

    IF v_handoff.status = 'COMPLETED' THEN
        RETURN v_handoff;
    END IF;

    IF v_actor = v_handoff.owner_user_id THEN
        UPDATE public.listing_handoffs
        SET owner_confirmed_at = COALESCE(owner_confirmed_at, v_now),
            status = CASE
                WHEN recipient_confirmed_at IS NOT NULL THEN 'COMPLETED'::handoff_status
                ELSE 'OWNER_CONFIRMED'::handoff_status
            END,
            completed_at = CASE
                WHEN recipient_confirmed_at IS NOT NULL THEN COALESCE(completed_at, v_now)
                ELSE completed_at
            END,
            updated_at = v_now
        WHERE id = p_handoff_id;
    ELSE
        UPDATE public.listing_handoffs
        SET recipient_confirmed_at = COALESCE(recipient_confirmed_at, v_now),
            status = CASE
                WHEN owner_confirmed_at IS NOT NULL THEN 'COMPLETED'::handoff_status
                ELSE 'RECIPIENT_CONFIRMED'::handoff_status
            END,
            completed_at = CASE
                WHEN owner_confirmed_at IS NOT NULL THEN COALESCE(completed_at, v_now)
                ELSE completed_at
            END,
            updated_at = v_now
        WHERE id = p_handoff_id;
    END IF;

    SELECT *
    INTO v_handoff
    FROM public.listing_handoffs
    WHERE id = p_handoff_id;

    IF v_handoff.status = 'COMPLETED' THEN
        SELECT *
        INTO v_listing
        FROM public.plant_listings
        WHERE id = v_handoff.listing_id
        FOR UPDATE;

        IF NOT FOUND THEN
            RAISE EXCEPTION 'Listing % does not exist', v_handoff.listing_id;
        END IF;

        UPDATE public.plant_listings
        SET status = 'COMPLETED',
            updated_at = v_now
        WHERE id = v_listing.id
          AND status <> 'COMPLETED';

        IF v_listing.listing_type IN ('SALE', 'GIFT') THEN
            UPDATE public.plants
            SET current_owner_user_id = v_handoff.recipient_user_id,
                updated_at = v_now
            WHERE id = v_listing.plant_id;
        ELSIF v_listing.listing_type = 'SWAP' THEN
            SELECT offered_plant_id
            INTO v_swap_offered_plant_id
            FROM public.swap_proposals
            WHERE id = v_handoff.swap_proposal_id
            FOR UPDATE;

            IF v_swap_offered_plant_id IS NULL THEN
                RAISE EXCEPTION 'Swap handoff % is missing its accepted proposal plant', p_handoff_id;
            END IF;

            UPDATE public.plants
            SET current_owner_user_id = v_handoff.recipient_user_id,
                updated_at = v_now
            WHERE id = v_listing.plant_id;

            UPDATE public.plants
            SET current_owner_user_id = v_handoff.owner_user_id,
                updated_at = v_now
            WHERE id = v_swap_offered_plant_id;

            UPDATE public.swap_proposals
            SET status = CASE
                    WHEN id = v_handoff.swap_proposal_id THEN 'COMPLETED'::swap_status
                    ELSE 'DECLINED'::swap_status
                END,
                responded_at = COALESCE(responded_at, v_now),
                updated_at = v_now
            WHERE listing_id = v_handoff.listing_id
              AND status IN ('PENDING', 'ACCEPTED');
        END IF;
    END IF;

    SELECT *
    INTO v_handoff
    FROM public.listing_handoffs
    WHERE id = p_handoff_id;

    RETURN v_handoff;
END;
$$;

GRANT EXECUTE ON FUNCTION public.confirm_listing_handoff(BIGINT) TO authenticated;

CREATE OR REPLACE FUNCTION public.validate_store_order()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
DECLARE
    v_listing_type listing_type;
    v_store_owner UUID;
    v_sale_price NUMERIC(10,2);
    v_currency CHAR(3);
BEGIN
    SELECT listing_type, store_owner_user_id, sale_price, currency_code
    INTO v_listing_type, v_store_owner, v_sale_price, v_currency
    FROM public.plant_listings
    WHERE id = NEW.listing_id;

    IF v_listing_type IS NULL THEN
        RAISE EXCEPTION 'Listing % does not exist', NEW.listing_id;
    END IF;

    IF v_listing_type <> 'SALE' THEN
        RAISE EXCEPTION 'Store orders are only valid for sale listings';
    END IF;

    IF v_store_owner IS NULL THEN
        RAISE EXCEPTION 'Peer sale listings must use listing_handoffs instead of store_orders';
    END IF;

    IF NEW.store_owner_user_id <> v_store_owner THEN
        RAISE EXCEPTION 'Store order owner must match listing store owner';
    END IF;

    IF NEW.amount <> v_sale_price OR NEW.currency_code <> v_currency THEN
        RAISE EXCEPTION 'Store order pricing must match the listing price';
    END IF;

    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_validate_store_order ON public.store_orders;
CREATE TRIGGER trg_validate_store_order
    BEFORE INSERT OR UPDATE ON public.store_orders
    FOR EACH ROW EXECUTE FUNCTION public.validate_store_order();

ALTER TABLE public.listing_handoffs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.listing_handoff_reviews ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "listing_applications_select" ON public.listing_applications;
CREATE POLICY "listing_applications_select"
  ON public.listing_applications FOR SELECT
  TO authenticated
  USING (
    applicant_user_id = auth.uid()
    OR EXISTS (
      SELECT 1 FROM public.plant_listings pl
      WHERE pl.id = listing_applications.listing_id
        AND pl.listing_type = 'SITTING_REQUEST'
        AND pl.owner_user_id = auth.uid()
    )
  );

DROP POLICY IF EXISTS "listing_applications_insert" ON public.listing_applications;
CREATE POLICY "listing_applications_insert"
  ON public.listing_applications FOR INSERT
  TO authenticated
  WITH CHECK (
    applicant_user_id = auth.uid()
    AND EXISTS (
      SELECT 1 FROM public.plant_listings pl
      WHERE pl.id = listing_applications.listing_id
        AND pl.listing_type = 'SITTING_REQUEST'
        AND pl.status = 'OPEN'
    )
  );

DROP POLICY IF EXISTS "listing_applications_update" ON public.listing_applications;
CREATE POLICY "listing_applications_update"
  ON public.listing_applications FOR UPDATE
  TO authenticated
  USING (
    applicant_user_id = auth.uid()
    OR EXISTS (
      SELECT 1 FROM public.plant_listings pl
      WHERE pl.id = listing_applications.listing_id
        AND pl.listing_type = 'SITTING_REQUEST'
        AND pl.owner_user_id = auth.uid()
    )
  )
  WITH CHECK (
    applicant_user_id = auth.uid()
    OR EXISTS (
      SELECT 1 FROM public.plant_listings pl
      WHERE pl.id = listing_applications.listing_id
        AND pl.listing_type = 'SITTING_REQUEST'
        AND pl.owner_user_id = auth.uid()
    )
  );

DROP POLICY IF EXISTS "swap_proposals_select" ON public.swap_proposals;
CREATE POLICY "swap_proposals_select"
  ON public.swap_proposals FOR SELECT
  TO authenticated
  USING (
    proposer_owner_user_id = auth.uid()
    OR EXISTS (
      SELECT 1 FROM public.plant_listings pl
      WHERE pl.id = swap_proposals.listing_id
        AND pl.listing_type = 'SWAP'
        AND pl.owner_user_id = auth.uid()
    )
  );

DROP POLICY IF EXISTS "swap_proposals_insert" ON public.swap_proposals;
CREATE POLICY "swap_proposals_insert"
  ON public.swap_proposals FOR INSERT
  TO authenticated
  WITH CHECK (
    proposer_owner_user_id = auth.uid()
    AND EXISTS (
      SELECT 1 FROM public.plant_listings pl
      WHERE pl.id = swap_proposals.listing_id
        AND pl.listing_type = 'SWAP'
        AND pl.status = 'OPEN'
    )
  );

DROP POLICY IF EXISTS "swap_proposals_update" ON public.swap_proposals;
CREATE POLICY "swap_proposals_update"
  ON public.swap_proposals FOR UPDATE
  TO authenticated
  USING (
    proposer_owner_user_id = auth.uid()
    OR EXISTS (
      SELECT 1 FROM public.plant_listings pl
      WHERE pl.id = swap_proposals.listing_id
        AND pl.listing_type = 'SWAP'
        AND pl.owner_user_id = auth.uid()
    )
  )
  WITH CHECK (
    proposer_owner_user_id = auth.uid()
    OR EXISTS (
      SELECT 1 FROM public.plant_listings pl
      WHERE pl.id = swap_proposals.listing_id
        AND pl.listing_type = 'SWAP'
        AND pl.owner_user_id = auth.uid()
    )
  );

DROP POLICY IF EXISTS "contracts_insert" ON public.contracts;
CREATE POLICY "contracts_insert"
  ON public.contracts FOR INSERT
  TO authenticated
  WITH CHECK (
    created_by_user_id = auth.uid()
    AND (owner_user_id = auth.uid() OR sitter_user_id = auth.uid())
  );

DROP POLICY IF EXISTS "contracts_update" ON public.contracts;
CREATE POLICY "contracts_update"
  ON public.contracts FOR UPDATE
  TO authenticated
  USING (owner_user_id = auth.uid() OR sitter_user_id = auth.uid())
  WITH CHECK (owner_user_id = auth.uid() OR sitter_user_id = auth.uid());

DROP POLICY IF EXISTS "listing_handoffs_select" ON public.listing_handoffs;
CREATE POLICY "listing_handoffs_select"
  ON public.listing_handoffs FOR SELECT
  TO authenticated
  USING (owner_user_id = auth.uid() OR recipient_user_id = auth.uid());

DROP POLICY IF EXISTS "plant_listings_select_open" ON public.plant_listings;
CREATE POLICY "plant_listings_select_open"
    ON public.plant_listings FOR SELECT
    TO authenticated
    USING (
        status = 'OPEN'
        OR owner_user_id = auth.uid()
        OR store_owner_user_id = auth.uid()
        OR EXISTS (
            SELECT 1 FROM public.listing_handoffs lh
            WHERE lh.listing_id = plant_listings.id
                AND (lh.owner_user_id = auth.uid() OR lh.recipient_user_id = auth.uid())
        )
    );

DROP POLICY IF EXISTS "listing_handoffs_insert" ON public.listing_handoffs;
CREATE POLICY "listing_handoffs_insert"
  ON public.listing_handoffs FOR INSERT
  TO authenticated
  WITH CHECK (
    created_by_user_id = auth.uid()
    AND (owner_user_id = auth.uid() OR recipient_user_id = auth.uid())
  );

DROP POLICY IF EXISTS "listing_handoffs_update" ON public.listing_handoffs;
CREATE POLICY "listing_handoffs_update"
  ON public.listing_handoffs FOR UPDATE
  TO authenticated
  USING (owner_user_id = auth.uid() OR recipient_user_id = auth.uid())
  WITH CHECK (owner_user_id = auth.uid() OR recipient_user_id = auth.uid());

DROP POLICY IF EXISTS "listing_handoff_reviews_select_authenticated" ON public.listing_handoff_reviews;
CREATE POLICY "listing_handoff_reviews_select_authenticated"
  ON public.listing_handoff_reviews FOR SELECT
  TO authenticated
  USING (true);

DROP POLICY IF EXISTS "listing_handoff_reviews_insert_own" ON public.listing_handoff_reviews;
CREATE POLICY "listing_handoff_reviews_insert_own"
  ON public.listing_handoff_reviews FOR INSERT
  TO authenticated
  WITH CHECK (
    reviewer_user_id = auth.uid()
    AND EXISTS (
      SELECT 1 FROM public.listing_handoffs lh
      WHERE lh.id = listing_handoff_reviews.handoff_id
        AND lh.status = 'COMPLETED'
        AND (
          (lh.owner_user_id = auth.uid() AND listing_handoff_reviews.reviewee_user_id = lh.recipient_user_id)
          OR
          (lh.recipient_user_id = auth.uid() AND listing_handoff_reviews.reviewee_user_id = lh.owner_user_id)
        )
    )
  );

DROP POLICY IF EXISTS "listing_handoff_reviews_update_own" ON public.listing_handoff_reviews;
CREATE POLICY "listing_handoff_reviews_update_own"
  ON public.listing_handoff_reviews FOR UPDATE
  TO authenticated
  USING (reviewer_user_id = auth.uid())
  WITH CHECK (reviewer_user_id = auth.uid());

CREATE INDEX IF NOT EXISTS idx_listing_handoffs_owner ON public.listing_handoffs(owner_user_id);
CREATE INDEX IF NOT EXISTS idx_listing_handoffs_recipient ON public.listing_handoffs(recipient_user_id);
CREATE INDEX IF NOT EXISTS idx_listing_handoffs_status ON public.listing_handoffs(status);
CREATE INDEX IF NOT EXISTS idx_listing_handoff_reviews_handoff_id ON public.listing_handoff_reviews(handoff_id);
CREATE INDEX IF NOT EXISTS idx_listing_handoff_reviews_reviewee ON public.listing_handoff_reviews(reviewee_user_id);

COMMIT;
