-- Adds deterministic common-plant care profiles for Add/Edit Plant autofill.
-- This is reference guidance only; users can edit every suggested value.

CREATE TABLE IF NOT EXISTS public.common_plant_care_profiles (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_key                 VARCHAR(120) NOT NULL UNIQUE,
    common_name                 VARCHAR(150) NOT NULL,
    scientific_name             VARCHAR(150) NOT NULL,
    aliases                     TEXT[] NOT NULL DEFAULT '{}',
    age_description             VARCHAR(100),
    watering_frequency_days     INTEGER NOT NULL,
    watering_frequency_unit     TEXT NOT NULL DEFAULT 'days',
    light_requirements          VARCHAR(120) NOT NULL,
    humidity_requirements       VARCHAR(120),
    location_notes              TEXT,
    care_notes                  TEXT,
    confidence_notes            TEXT,
    is_active                   BOOLEAN NOT NULL DEFAULT TRUE,
    sort_order                  INTEGER NOT NULL DEFAULT 0,
    created_at                  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at                  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT common_plant_care_profiles_watering_chk CHECK (watering_frequency_days > 0),
    CONSTRAINT common_plant_care_profiles_watering_unit_chk CHECK (watering_frequency_unit IN ('days', 'weeks', 'months')),
    CONSTRAINT common_plant_care_profiles_age_chk CHECK (
        age_description IS NULL OR age_description IN (
            'Cutting / propagation',
            'Seedling',
            'Young plant',
            'Mature plant',
            'Established plant'
        )
    )
);

CREATE INDEX IF NOT EXISTS idx_common_plant_care_profiles_active
    ON public.common_plant_care_profiles(is_active, sort_order);

ALTER TABLE public.common_plant_care_profiles ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "common_plant_care_profiles_select_authenticated"
  ON public.common_plant_care_profiles;

CREATE POLICY "common_plant_care_profiles_select_authenticated"
  ON public.common_plant_care_profiles FOR SELECT
  TO authenticated
  USING (is_active = TRUE);

INSERT INTO public.common_plant_care_profiles (
    profile_key,
    common_name,
    scientific_name,
    aliases,
    age_description,
    watering_frequency_days,
    watering_frequency_unit,
    light_requirements,
    humidity_requirements,
    location_notes,
    care_notes,
    confidence_notes,
    sort_order
) VALUES
('monstera-deliciosa', 'Monstera', 'Monstera deliciosa', ARRAY['Swiss cheese plant', 'Monstera'], NULL, 7, 'days', 'Bright indirect light', 'Medium to high humidity', 'Near a bright window away from harsh direct sun', 'Let the top layer of soil dry before watering; rotate for even growth.', 'General indoor guidance; adjust for pot size, soil, and season.', 10),
('monstera-deliciosa-seedling', 'Monstera', 'Monstera deliciosa', ARRAY['Swiss cheese plant seedling', 'Young monstera'], 'Seedling', 5, 'days', 'Bright indirect light', 'High humidity', 'Warm bright spot away from drafts', 'Keep soil lightly moist but never soggy while roots establish.', 'Age-specific guidance for smaller developing plants.', 11),
('epipremnum-aureum', 'Pothos', 'Epipremnum aureum', ARRAY['Devil''s ivy', 'Golden pothos'], NULL, 10, 'days', 'Low to bright indirect light', 'Average household humidity', 'Shelf, hanging basket, or indirect window light', 'Allow soil to dry partway between waterings; trim vines to encourage fullness.', 'Tolerant plant; water needs vary strongly by light level.', 20),
('sansevieria-trifasciata', 'Snake plant', 'Dracaena trifasciata', ARRAY['Sansevieria', 'Mother-in-law''s tongue'], NULL, 3, 'weeks', 'Low to bright indirect light', 'Low to average humidity', 'Bedroom, hallway, or bright room with indirect light', 'Water sparingly and avoid leaving water in the crown.', 'Drought-tolerant; overwatering is the main risk.', 30),
('chlorophytum-comosum', 'Spider plant', 'Chlorophytum comosum', ARRAY['Spider ivy', 'Ribbon plant'], NULL, 7, 'days', 'Bright indirect light', 'Average household humidity', 'Bright room or window with filtered light', 'Water when the top soil begins to dry; remove brown tips with clean scissors.', 'Usually forgiving in average indoor conditions.', 40),
('spathiphyllum', 'Peace lily', 'Spathiphyllum', ARRAY['Spathiphyllum wallisii'], NULL, 7, 'days', 'Medium to bright indirect light', 'Medium to high humidity', 'Bathroom or bright room away from direct sun', 'Water when leaves begin to soften slightly; avoid letting it stay fully dry.', 'Sensitive to underwatering and harsh direct sun.', 50),
('zamioculcas-zamiifolia', 'ZZ plant', 'Zamioculcas zamiifolia', ARRAY['Zanzibar gem', 'ZZ'], NULL, 3, 'weeks', 'Low to bright indirect light', 'Low to average humidity', 'Low-light room or office with indirect light', 'Let soil dry thoroughly between waterings.', 'Very drought-tolerant; reduce watering in winter.', 60),
('ficus-lyrata', 'Fiddle leaf fig', 'Ficus lyrata', ARRAY['Fiddle fig'], NULL, 10, 'days', 'Bright indirect light', 'Average to medium humidity', 'Stable bright spot away from drafts and vents', 'Water when the top soil dries; avoid frequent moves.', 'Can be sensitive to changes in light, drafts, and watering.', 70),
('ficus-elastica', 'Rubber plant', 'Ficus elastica', ARRAY['Rubber tree'], NULL, 10, 'days', 'Bright indirect light', 'Average household humidity', 'Bright room with filtered light', 'Let the top soil dry between waterings; wipe leaves occasionally.', 'Generally adaptable, but avoid soggy soil.', 80),
('aloe-vera', 'Aloe vera', 'Aloe vera', ARRAY['Aloe'], NULL, 3, 'weeks', 'Bright direct to bright indirect light', 'Low humidity', 'Sunny windowsill or very bright room', 'Water deeply, then let soil dry fully before watering again.', 'Succulent guidance; requires very well-draining soil.', 90),
('calathea-orbifolia', 'Calathea', 'Goeppertia orbifolia', ARRAY['Prayer plant', 'Calathea orbifolia'], NULL, 6, 'days', 'Medium indirect light', 'High humidity', 'Warm room away from direct sun and cold drafts', 'Keep soil evenly lightly moist; use filtered water if leaf edges brown.', 'Humidity and water quality matter more than for many houseplants.', 100),
('phalaenopsis', 'Moth orchid', 'Phalaenopsis', ARRAY['Phalaenopsis orchid', 'Orchid'], NULL, 7, 'days', 'Bright indirect light', 'Medium to high humidity', 'Bright windowsill with filtered light', 'Water the potting medium when nearly dry; avoid water sitting in the crown.', 'Assumes bark or orchid mix, not regular potting soil.', 110),
('crassula-ovata', 'Jade plant', 'Crassula ovata', ARRAY['Jade', 'Money plant'], NULL, 3, 'weeks', 'Bright light with some direct sun', 'Low humidity', 'Sunny windowsill or bright room', 'Water only when soil is fully dry; use a pot with drainage.', 'Succulent guidance; reduce watering in cooler months.', 120),
('nephrolepis-exaltata', 'Boston fern', 'Nephrolepis exaltata', ARRAY['Sword fern'], NULL, 5, 'days', 'Medium to bright indirect light', 'High humidity', 'Bathroom, kitchen, or humid bright room', 'Keep soil consistently lightly moist and avoid dry air.', 'May need more frequent watering in warm dry rooms.', 130),
('pilea-peperomioides', 'Chinese money plant', 'Pilea peperomioides', ARRAY['Pilea', 'UFO plant', 'Pancake plant'], NULL, 7, 'days', 'Bright indirect light', 'Average household humidity', 'Bright windowsill with filtered light', 'Let the top soil dry between waterings; rotate for even growth.', 'Usually straightforward in bright indirect light.', 140)
ON CONFLICT (profile_key) DO UPDATE SET
    common_name = EXCLUDED.common_name,
    scientific_name = EXCLUDED.scientific_name,
    aliases = EXCLUDED.aliases,
    age_description = EXCLUDED.age_description,
    watering_frequency_days = EXCLUDED.watering_frequency_days,
    watering_frequency_unit = EXCLUDED.watering_frequency_unit,
    light_requirements = EXCLUDED.light_requirements,
    humidity_requirements = EXCLUDED.humidity_requirements,
    location_notes = EXCLUDED.location_notes,
    care_notes = EXCLUDED.care_notes,
    confidence_notes = EXCLUDED.confidence_notes,
    sort_order = EXCLUDED.sort_order,
    is_active = TRUE,
    updated_at = NOW();
