BEGIN;

CREATE EXTENSION IF NOT EXISTS citext;

-- =========================================================
-- ENUMS
-- =========================================================

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'user_status') THEN
        CREATE TYPE user_status AS ENUM ('ACTIVE', 'SUSPENDED', 'DEACTIVATED', 'PENDING_VERIFICATION');
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'listing_type') THEN
        CREATE TYPE listing_type AS ENUM ('SITTING_REQUEST', 'DONATION', 'SWAP', 'SALE');
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'listing_status') THEN
        CREATE TYPE listing_status AS ENUM ('DRAFT', 'OPEN', 'PAUSED', 'MATCHED', 'COMPLETED', 'CANCELLED', 'ARCHIVED');
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'application_status') THEN
        CREATE TYPE application_status AS ENUM ('PENDING', 'ACCEPTED', 'DECLINED', 'WITHDRAWN', 'EXPIRED');
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'swap_status') THEN
        CREATE TYPE swap_status AS ENUM ('PENDING', 'ACCEPTED', 'DECLINED', 'CANCELLED', 'COMPLETED');
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'contract_status') THEN
        CREATE TYPE contract_status AS ENUM ('DRAFT', 'PENDING_OWNER', 'PENDING_SITTER', 'ACTIVE', 'COMPLETED', 'CANCELLED', 'DISPUTED');
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'message_type') THEN
        CREATE TYPE message_type AS ENUM ('TEXT', 'SYSTEM', 'IMAGE', 'FILE');
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'notification_type') THEN
        CREATE TYPE notification_type AS ENUM (
            'APPLICATION_RECEIVED',
            'APPLICATION_ACCEPTED',
            'APPLICATION_DECLINED',
            'SWAP_PROPOSAL_RECEIVED',
            'SWAP_PROPOSAL_ACCEPTED',
            'SWAP_PROPOSAL_DECLINED',
            'CONTRACT_CREATED',
            'CONTRACT_ACCEPTED',
            'MESSAGE_RECEIVED',
            'ORDER_CREATED',
            'PAYMENT_POSTED',
            'SYSTEM_ALERT'
        );
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'payment_direction') THEN
        CREATE TYPE payment_direction AS ENUM ('DEBIT', 'CREDIT');
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'payment_status') THEN
        CREATE TYPE payment_status AS ENUM ('PENDING', 'AUTHORIZED', 'SETTLED', 'FAILED', 'REFUNDED', 'VOIDED');
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'availability_status') THEN
        CREATE TYPE availability_status AS ENUM ('AVAILABLE', 'UNAVAILABLE', 'BOOKED', 'TENTATIVE');
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'attachment_kind') THEN
        CREATE TYPE attachment_kind AS ENUM ('IMAGE', 'VIDEO', 'DOCUMENT', 'OTHER');
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'moderation_status') THEN
        CREATE TYPE moderation_status AS ENUM ('OPEN', 'UNDER_REVIEW', 'ACTION_TAKEN', 'DISMISSED');
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'order_status') THEN
        CREATE TYPE order_status AS ENUM ('PENDING', 'PAID', 'FULFILLED', 'CANCELLED', 'REFUNDED');
    END IF;
END$$;

-- =========================================================
-- USERS + ROLE PROFILES
-- =========================================================

CREATE TABLE IF NOT EXISTS users (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username                    CITEXT NOT NULL UNIQUE,
    email                       CITEXT NOT NULL UNIQUE,
    password_hash               VARCHAR(255) NOT NULL,
    phone_number                VARCHAR(30),
    first_name                  VARCHAR(100),
    last_name                   VARCHAR(100),
    bio                         TEXT,
    city                        VARCHAR(120),
    region                      VARCHAR(120),
    country_code                CHAR(2),
    profile_photo_url           TEXT,
    status                      user_status NOT NULL DEFAULT 'PENDING_VERIFICATION',
    email_verified_at           TIMESTAMPTZ,
    last_login_at               TIMESTAMPTZ,
    created_at                  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at                  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at                  TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS owner_profiles (
    user_id                     BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    display_name                VARCHAR(120),
    address_line_1              VARCHAR(255),
    address_line_2              VARCHAR(255),
    postal_code                 VARCHAR(30),
    emergency_contact_name      VARCHAR(120),
    emergency_contact_phone     VARCHAR(30),
    created_at                  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at                  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS sitter_profiles (
    user_id                     BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    display_name                VARCHAR(120),
    experience_summary          TEXT,
    years_experience            INTEGER,
    base_daily_rate             NUMERIC(10,2),
    rating_average              NUMERIC(3,2) NOT NULL DEFAULT 0.00,
    rating_count                INTEGER NOT NULL DEFAULT 0,
    can_travel                  BOOLEAN NOT NULL DEFAULT FALSE,
    travel_radius_km            INTEGER,
    identity_verified_at        TIMESTAMPTZ,
    created_at                  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at                  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT sitter_profiles_years_chk CHECK (years_experience IS NULL OR years_experience >= 0),
    CONSTRAINT sitter_profiles_rate_chk CHECK (base_daily_rate IS NULL OR base_daily_rate >= 0)
);

CREATE TABLE IF NOT EXISTS store_owner_profiles (
    user_id                     BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    store_name                  VARCHAR(180) NOT NULL,
    business_email              CITEXT,
    business_phone              VARCHAR(30),
    business_address_line_1     VARCHAR(255),
    business_address_line_2     VARCHAR(255),
    business_postal_code        VARCHAR(30),
    tax_identifier              VARCHAR(100),
    payout_account_ref          VARCHAR(255),
    approved_at                 TIMESTAMPTZ,
    approved_by_user_id         BIGINT REFERENCES users(id) ON DELETE SET NULL,
    approval_notes              TEXT,
    is_approved                 BOOLEAN NOT NULL DEFAULT FALSE,
    created_at                  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at                  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =========================================================
-- PLANTS
-- =========================================================

CREATE TABLE IF NOT EXISTS plants (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    current_owner_user_id       BIGINT NOT NULL REFERENCES owner_profiles(user_id) ON DELETE RESTRICT,
    name                        VARCHAR(150) NOT NULL,
    species                     VARCHAR(150),
    description                 TEXT,
    age_description             VARCHAR(100),
    size_description            VARCHAR(100),
    health_status               VARCHAR(100),
    watering_frequency_days     INTEGER,
    light_requirements          VARCHAR(120),
    humidity_requirements       VARCHAR(120),
    special_instructions        TEXT,
    location_notes              TEXT,
    is_active                   BOOLEAN NOT NULL DEFAULT TRUE,
    created_at                  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at                  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    archived_at                 TIMESTAMPTZ,
    CONSTRAINT plants_watering_chk CHECK (watering_frequency_days IS NULL OR watering_frequency_days > 0)
);

CREATE TABLE IF NOT EXISTS plant_photos (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plant_id                    BIGINT NOT NULL REFERENCES plants(id) ON DELETE CASCADE,
    storage_key                 TEXT NOT NULL,
    public_url                  TEXT,
    content_type                VARCHAR(100),
    file_size_bytes             BIGINT,
    sort_order                  INTEGER NOT NULL DEFAULT 0,
    uploaded_by_user_id         BIGINT REFERENCES users(id) ON DELETE SET NULL,
    created_at                  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS plant_care_tasks (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plant_id                    BIGINT NOT NULL REFERENCES plants(id) ON DELETE CASCADE,
    task_name                   VARCHAR(150) NOT NULL,
    instructions                TEXT,
    frequency_days              INTEGER,
    preferred_time_note         VARCHAR(120),
    is_required                 BOOLEAN NOT NULL DEFAULT TRUE,
    created_at                  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at                  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =========================================================
-- PLANT LISTINGS
-- owner: sitting request / donation / swap
-- store owner: sale
-- =========================================================

CREATE TABLE IF NOT EXISTS plant_listings (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plant_id                    BIGINT NOT NULL REFERENCES plants(id) ON DELETE CASCADE,
    listing_type                listing_type NOT NULL,
    status                      listing_status NOT NULL DEFAULT 'DRAFT',

    owner_user_id               BIGINT REFERENCES owner_profiles(user_id) ON DELETE CASCADE,
    store_owner_user_id         BIGINT REFERENCES store_owner_profiles(user_id) ON DELETE CASCADE,

    title                       VARCHAR(200) NOT NULL,
    description                 TEXT,

    desired_swap_notes          TEXT,
    donation_notes              TEXT,
    sitting_start_date          DATE,
    sitting_end_date            DATE,
    sitting_notes               TEXT,

    sale_price                  NUMERIC(10,2),
    currency_code               CHAR(3),

    created_at                  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at                  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    published_at                TIMESTAMPTZ,
    closed_at                   TIMESTAMPTZ,

    CONSTRAINT plant_listings_sale_price_chk
        CHECK (sale_price IS NULL OR sale_price >= 0),

    CONSTRAINT plant_listings_sitting_dates_chk
        CHECK (
            sitting_start_date IS NULL
            OR sitting_end_date IS NULL
            OR sitting_end_date >= sitting_start_date
        ),

    CONSTRAINT plant_listings_owner_or_store_chk
        CHECK (
            (owner_user_id IS NOT NULL AND store_owner_user_id IS NULL)
            OR
            (owner_user_id IS NULL AND store_owner_user_id IS NOT NULL)
        ),

    CONSTRAINT plant_listings_sale_requires_store_chk
        CHECK (
            (listing_type <> 'SALE')
            OR
            (store_owner_user_id IS NOT NULL AND sale_price IS NOT NULL AND currency_code IS NOT NULL)
        ),

    CONSTRAINT plant_listings_non_sale_requires_owner_chk
        CHECK (
            (listing_type = 'SALE')
            OR
            (owner_user_id IS NOT NULL)
        )
);

-- =========================================================
-- APPLICATIONS
-- Used for:
-- - sitter applying to sitting request
-- - sitter expressing interest in donation
-- =========================================================

CREATE TABLE IF NOT EXISTS listing_applications (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    listing_id                  BIGINT NOT NULL REFERENCES plant_listings(id) ON DELETE CASCADE,
    applicant_user_id           BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    message_to_lister           TEXT,
    proposed_start_date         DATE,
    proposed_end_date           DATE,
    proposed_price              NUMERIC(10,2),
    status                      application_status NOT NULL DEFAULT 'PENDING',
    responded_at                TIMESTAMPTZ,
    created_at                  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at                  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT listing_applications_price_chk CHECK (proposed_price IS NULL OR proposed_price >= 0),
    CONSTRAINT listing_applications_dates_chk CHECK (
        proposed_start_date IS NULL
        OR proposed_end_date IS NULL
        OR proposed_end_date >= proposed_start_date
    ),
    CONSTRAINT listing_applications_unique UNIQUE (listing_id, applicant_user_id)
);

-- =========================================================
-- SWAP PROPOSALS
-- owner responds to owner swap listing with another plant
-- =========================================================

CREATE TABLE IF NOT EXISTS swap_proposals (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    listing_id                  BIGINT NOT NULL REFERENCES plant_listings(id) ON DELETE CASCADE,
    proposer_owner_user_id      BIGINT NOT NULL REFERENCES owner_profiles(user_id) ON DELETE CASCADE,
    offered_plant_id            BIGINT NOT NULL REFERENCES plants(id) ON DELETE RESTRICT,
    message_to_owner            TEXT,
    status                      swap_status NOT NULL DEFAULT 'PENDING',
    responded_at                TIMESTAMPTZ,
    created_at                  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at                  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT swap_proposals_unique UNIQUE (listing_id, proposer_owner_user_id, offered_plant_id)
);

-- =========================================================
-- SITTING CONTRACTS
-- only for confirmed sitting arrangements
-- =========================================================

CREATE TABLE IF NOT EXISTS contracts (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    listing_id                  BIGINT REFERENCES plant_listings(id) ON DELETE SET NULL,
    application_id              BIGINT UNIQUE REFERENCES listing_applications(id) ON DELETE SET NULL,
    owner_user_id               BIGINT NOT NULL REFERENCES owner_profiles(user_id) ON DELETE RESTRICT,
    sitter_user_id              BIGINT NOT NULL REFERENCES sitter_profiles(user_id) ON DELETE RESTRICT,
    title                       VARCHAR(200),
    description                 TEXT,
    start_date                  DATE NOT NULL,
    end_date                    DATE NOT NULL,
    agreed_price                NUMERIC(10,2) NOT NULL DEFAULT 0.00,
    currency_code               CHAR(3) NOT NULL DEFAULT 'USD',
    status                      contract_status NOT NULL DEFAULT 'DRAFT',
    owner_accepted_at           TIMESTAMPTZ,
    sitter_accepted_at          TIMESTAMPTZ,
    cancelled_at                TIMESTAMPTZ,
    completed_at                TIMESTAMPTZ,
    created_by_user_id          BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    created_at                  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at                  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT contracts_dates_chk CHECK (end_date >= start_date),
    CONSTRAINT contracts_price_chk CHECK (agreed_price >= 0),
    CONSTRAINT contracts_distinct_parties_chk CHECK (owner_user_id <> sitter_user_id)
);

CREATE TABLE IF NOT EXISTS contract_plants (
    contract_id                 BIGINT NOT NULL REFERENCES contracts(id) ON DELETE CASCADE,
    plant_id                    BIGINT NOT NULL REFERENCES plants(id) ON DELETE RESTRICT,
    created_at                  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (contract_id, plant_id)
);

-- =========================================================
-- STORE SALES
-- =========================================================

CREATE TABLE IF NOT EXISTS store_orders (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    listing_id                  BIGINT NOT NULL REFERENCES plant_listings(id) ON DELETE RESTRICT,
    buyer_user_id               BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    store_owner_user_id         BIGINT NOT NULL REFERENCES store_owner_profiles(user_id) ON DELETE RESTRICT,
    amount                      NUMERIC(10,2) NOT NULL,
    currency_code               CHAR(3) NOT NULL DEFAULT 'USD',
    status                      order_status NOT NULL DEFAULT 'PENDING',
    created_at                  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    paid_at                     TIMESTAMPTZ,
    fulfilled_at                TIMESTAMPTZ,
    cancelled_at                TIMESTAMPTZ,
    CONSTRAINT store_orders_amount_chk CHECK (amount >= 0)
);

-- =========================================================
-- CONVERSATIONS / MESSAGES
-- =========================================================

CREATE TABLE IF NOT EXISTS conversations (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    listing_id                  BIGINT REFERENCES plant_listings(id) ON DELETE SET NULL,
    contract_id                 BIGINT REFERENCES contracts(id) ON DELETE SET NULL,
    order_id                    BIGINT REFERENCES store_orders(id) ON DELETE SET NULL,
    created_at                  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at                  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_message_at             TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS conversation_participants (
    conversation_id             BIGINT NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
    user_id                     BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    joined_at                   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (conversation_id, user_id)
);

CREATE TABLE IF NOT EXISTS messages (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id             BIGINT NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
    sender_user_id              BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    message_type                message_type NOT NULL DEFAULT 'TEXT',
    body                        TEXT,
    is_edited                   BOOLEAN NOT NULL DEFAULT FALSE,
    edited_at                   TIMESTAMPTZ,
    delivered_at                TIMESTAMPTZ,
    read_at                     TIMESTAMPTZ,
    created_at                  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at                  TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS message_attachments (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id                  BIGINT NOT NULL REFERENCES messages(id) ON DELETE CASCADE,
    attachment_kind             attachment_kind NOT NULL,
    original_filename           VARCHAR(255),
    storage_key                 TEXT NOT NULL,
    public_url                  TEXT,
    content_type                VARCHAR(100),
    file_size_bytes             BIGINT,
    image_width                 INTEGER,
    image_height                INTEGER,
    checksum_sha256             VARCHAR(128),
    created_at                  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =========================================================
-- NOTIFICATIONS
-- =========================================================

CREATE TABLE IF NOT EXISTS notifications (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                     BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    notification_type           notification_type NOT NULL,
    title                       VARCHAR(200) NOT NULL,
    body                        TEXT,
    related_listing_id          BIGINT REFERENCES plant_listings(id) ON DELETE SET NULL,
    related_application_id      BIGINT REFERENCES listing_applications(id) ON DELETE SET NULL,
    related_swap_proposal_id    BIGINT REFERENCES swap_proposals(id) ON DELETE SET NULL,
    related_contract_id         BIGINT REFERENCES contracts(id) ON DELETE SET NULL,
    related_order_id            BIGINT REFERENCES store_orders(id) ON DELETE SET NULL,
    related_message_id          BIGINT REFERENCES messages(id) ON DELETE SET NULL,
    is_read                     BOOLEAN NOT NULL DEFAULT FALSE,
    read_at                     TIMESTAMPTZ,
    created_at                  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =========================================================
-- PAYMENTS / LEDGER
-- =========================================================

CREATE TABLE IF NOT EXISTS payment_ledger (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contract_id                 BIGINT REFERENCES contracts(id) ON DELETE SET NULL,
    order_id                    BIGINT REFERENCES store_orders(id) ON DELETE SET NULL,
    payer_user_id               BIGINT REFERENCES users(id) ON DELETE RESTRICT,
    payee_user_id               BIGINT REFERENCES users(id) ON DELETE RESTRICT,
    direction                   payment_direction NOT NULL,
    amount                      NUMERIC(12,2) NOT NULL,
    currency_code               CHAR(3) NOT NULL DEFAULT 'USD',
    status                      payment_status NOT NULL DEFAULT 'PENDING',
    external_reference          VARCHAR(255),
    notes                       TEXT,
    occurred_at                 TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_at                  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT payment_ledger_amount_chk CHECK (amount >= 0)
);

-- =========================================================
-- AVAILABILITY
-- =========================================================

CREATE TABLE IF NOT EXISTS sitter_availability (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sitter_user_id              BIGINT NOT NULL REFERENCES sitter_profiles(user_id) ON DELETE CASCADE,
    start_at                    TIMESTAMPTZ NOT NULL,
    end_at                      TIMESTAMPTZ NOT NULL,
    status                      availability_status NOT NULL DEFAULT 'AVAILABLE',
    notes                       TEXT,
    created_at                  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at                  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT sitter_availability_time_chk CHECK (end_at > start_at)
);

-- =========================================================
-- AUTH / REVIEWS / MODERATION / AUDIT
-- =========================================================

CREATE TABLE IF NOT EXISTS refresh_tokens (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                     BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token_hash                  VARCHAR(255) NOT NULL UNIQUE,
    expires_at                  TIMESTAMPTZ NOT NULL,
    revoked_at                  TIMESTAMPTZ,
    replaced_by_token_hash      VARCHAR(255),
    created_at                  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    user_agent                  TEXT,
    ip_address                  INET
);

CREATE TABLE IF NOT EXISTS sitter_reviews (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contract_id                 BIGINT NOT NULL UNIQUE REFERENCES contracts(id) ON DELETE CASCADE,
    sitter_user_id              BIGINT NOT NULL REFERENCES sitter_profiles(user_id) ON DELETE CASCADE,
    owner_user_id               BIGINT NOT NULL REFERENCES owner_profiles(user_id) ON DELETE CASCADE,
    rating                      INTEGER NOT NULL CHECK (rating BETWEEN 1 AND 5),
    review_text                 TEXT,
    created_at                  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at                  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS moderation_cases (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reported_by_user_id         BIGINT REFERENCES users(id) ON DELETE SET NULL,
    target_user_id              BIGINT REFERENCES users(id) ON DELETE SET NULL,
    target_message_id           BIGINT REFERENCES messages(id) ON DELETE SET NULL,
    target_contract_id          BIGINT REFERENCES contracts(id) ON DELETE SET NULL,
    target_listing_id           BIGINT REFERENCES plant_listings(id) ON DELETE SET NULL,
    reason                      VARCHAR(255) NOT NULL,
    description                 TEXT,
    status                      moderation_status NOT NULL DEFAULT 'OPEN',
    reviewed_by_user_id         BIGINT REFERENCES users(id) ON DELETE SET NULL,
    reviewed_at                 TIMESTAMPTZ,
    created_at                  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at                  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS audit_log (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_user_id               BIGINT REFERENCES users(id) ON DELETE SET NULL,
    action_type                 VARCHAR(100) NOT NULL,
    target_table                VARCHAR(100) NOT NULL,
    target_id                   BIGINT,
    metadata_json               JSONB,
    ip_address                  INET,
    created_at                  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =========================================================
-- INDEXES
-- =========================================================

CREATE INDEX IF NOT EXISTS idx_plants_current_owner ON plants(current_owner_user_id);

CREATE INDEX IF NOT EXISTS idx_plant_listings_plant_id ON plant_listings(plant_id);
CREATE INDEX IF NOT EXISTS idx_plant_listings_type ON plant_listings(listing_type);
CREATE INDEX IF NOT EXISTS idx_plant_listings_status ON plant_listings(status);
CREATE INDEX IF NOT EXISTS idx_plant_listings_owner_user_id ON plant_listings(owner_user_id);
CREATE INDEX IF NOT EXISTS idx_plant_listings_store_owner_user_id ON plant_listings(store_owner_user_id);

CREATE INDEX IF NOT EXISTS idx_listing_applications_listing_id ON listing_applications(listing_id);
CREATE INDEX IF NOT EXISTS idx_listing_applications_applicant_user_id ON listing_applications(applicant_user_id);
CREATE INDEX IF NOT EXISTS idx_listing_applications_status ON listing_applications(status);

CREATE INDEX IF NOT EXISTS idx_swap_proposals_listing_id ON swap_proposals(listing_id);
CREATE INDEX IF NOT EXISTS idx_swap_proposals_proposer_owner ON swap_proposals(proposer_owner_user_id);
CREATE INDEX IF NOT EXISTS idx_swap_proposals_status ON swap_proposals(status);

CREATE INDEX IF NOT EXISTS idx_contracts_owner ON contracts(owner_user_id);
CREATE INDEX IF NOT EXISTS idx_contracts_sitter ON contracts(sitter_user_id);
CREATE INDEX IF NOT EXISTS idx_contracts_status ON contracts(status);

CREATE INDEX IF NOT EXISTS idx_store_orders_listing_id ON store_orders(listing_id);
CREATE INDEX IF NOT EXISTS idx_store_orders_buyer ON store_orders(buyer_user_id);
CREATE INDEX IF NOT EXISTS idx_store_orders_store_owner ON store_orders(store_owner_user_id);
CREATE INDEX IF NOT EXISTS idx_store_orders_status ON store_orders(status);

CREATE INDEX IF NOT EXISTS idx_messages_conversation_id ON messages(conversation_id);
CREATE INDEX IF NOT EXISTS idx_notifications_user_id ON notifications(user_id);
CREATE INDEX IF NOT EXISTS idx_payment_ledger_contract_id ON payment_ledger(contract_id);
CREATE INDEX IF NOT EXISTS idx_payment_ledger_order_id ON payment_ledger(order_id);
CREATE INDEX IF NOT EXISTS idx_sitter_availability_sitter_user_id ON sitter_availability(sitter_user_id);

COMMIT;